### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by VortexIncAdmin** [MichaelTheShifter/Memphis2#4]
Is Memphis2 Open Source? Thanks! BTW I am a fan of OSFirstTimer and the ShiftOS channel. ;)

**Comment by mihail-mojsoski** [comment]
Well, it's Opensource.
But i'm not sure what licence it uses, because there is no Licence file in the project.

**Comment by VortexIncAdmin** [comment]
OK.

**Comment by MichaelTheShifter** [comment]
This project is postponed until I can get the netcore version of Cosmos
working properly. But, Memphis is licensed under the MIT license (just like
ShiftOS.)
